# Generated by Django 2.1.2 on 2018-11-08 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='district',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='number',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Mobile number not valid. Must have minimum 11 digits.', regex='[+]?\\d+')]),
        ),
        migrations.AlterField(
            model_name='thana',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Thana'),
        ),
    ]
